/*
FORALL is used to perform bulk DML operations (INSERT, UPDATE, DELETE) on collections, which minimizes context switching.
*/
/*
TODO Need to correct the procedure
*/
CREATE OR REPLACE PROCEDURE BULK_EXCEPTION_HANDLING AS
    TYPE SALES_RECORD_TYPE IS TABLE OF SALES%ROWTYPE;
    L_SALES_RECORDS SALES_RECORD_TYPE;
    CURSOR SALES_CURSOR IS SELECT * FROM SALES;
BEGIN
    OPEN SALES_CURSOR;

    LOOP
        FETCH SALES_CURSOR BULK COLLECT INTO L_SALES_RECORDS LIMIT 100;
        EXIT WHEN L_SALES_RECORDS.COUNT = 0;

        FORALL i IN 1 .. L_SALES_RECORDS.COUNT SAVE EXCEPTIONS
            INSERT INTO SALES_2 VALUES L_SALES_RECORDS(i);
    END LOOP;

    CLOSE SALES_CURSOR;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -24381 THEN
            FOR i IN 1 .. SQL%BULK_EXCEPTIONS.COUNT LOOP
                DBMS_OUTPUT.PUT_LINE('Error Index: ' || SQL%BULK_EXCEPTIONS(i).ERROR_INDEX);
                DBMS_OUTPUT.PUT_LINE('Error Message: ' || SQLERRM(-SQL%BULK_EXCEPTIONS(i).ERROR_CODE));
            END LOOP;
        ELSE
            RAISE;
        END IF;
END;
/
BEGIN
    BULK_EXCEPTION_HANDLING;
END;
/